
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
  {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 8080